[2024-07-24T05:34:15.573+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T05:34:15.583+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_to_postgres_dag.transfer_csv_to_db manual__2024-07-24T05:34:14.147444+00:00 [queued]>
[2024-07-24T05:34:15.587+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_to_postgres_dag.transfer_csv_to_db manual__2024-07-24T05:34:14.147444+00:00 [queued]>
[2024-07-24T05:34:15.587+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-24T05:34:15.592+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transfer_csv_to_db> on 2024-07-24 05:34:14.147444+00:00
[2024-07-24T05:34:15.595+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=624) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T05:34:15.595+0000] {standard_task_runner.py:64} INFO - Started process 625 to run task
[2024-07-24T05:34:15.596+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3_to_postgres_dag', 'transfer_csv_to_db', 'manual__2024-07-24T05:34:14.147444+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/accommodations.py', '--cfg-path', '/tmp/tmpq5_3ztj2']
[2024-07-24T05:34:15.597+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask transfer_csv_to_db
[2024-07-24T05:34:15.632+0000] {task_command.py:426} INFO - Running <TaskInstance: s3_to_postgres_dag.transfer_csv_to_db manual__2024-07-24T05:34:14.147444+00:00 [running]> on host 7f96a5b4d944
[2024-07-24T05:34:15.711+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_to_postgres_dag' AIRFLOW_CTX_TASK_ID='transfer_csv_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T05:34:14.147444+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-24T05:34:14.147444+00:00'
[2024-07-24T05:34:15.712+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T05:34:15.736+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2024-07-24T05:34:15.737+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-07-24T05:34:16.047+0000] {logging_mixin.py:188} INFO - Error: relation "your_table" does not exist
LINE 1: INSERT INTO your_table ("ï»¿relevance", "id", "title", "descri...
                    ^
[2024-07-24T05:34:16.053+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-24T05:34:16.055+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T05:34:16.071+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=s3_to_postgres_dag, task_id=transfer_csv_to_db, run_id=manual__2024-07-24T05:34:14.147444+00:00, execution_date=20240724T053414, start_date=20240724T053415, end_date=20240724T053416
[2024-07-24T05:34:16.129+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T05:34:16.165+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T05:34:16.168+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
