[2024-07-24T06:52:32.282+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T06:52:32.291+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_file_import_dag.get_s3_data manual__2024-07-24T06:52:30.704734+00:00 [queued]>
[2024-07-24T06:52:32.295+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_file_import_dag.get_s3_data manual__2024-07-24T06:52:30.704734+00:00 [queued]>
[2024-07-24T06:52:32.296+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-24T06:52:32.308+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_s3_data> on 2024-07-24 06:52:30.704734+00:00
[2024-07-24T06:52:32.314+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1808) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T06:52:32.315+0000] {standard_task_runner.py:64} INFO - Started process 1810 to run task
[2024-07-24T06:52:32.315+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3_file_import_dag', 'get_s3_data', 'manual__2024-07-24T06:52:30.704734+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/accommodations.py', '--cfg-path', '/tmp/tmpsb660jsj']
[2024-07-24T06:52:32.317+0000] {standard_task_runner.py:91} INFO - Job 84: Subtask get_s3_data
[2024-07-24T06:52:32.353+0000] {task_command.py:426} INFO - Running <TaskInstance: s3_file_import_dag.get_s3_data manual__2024-07-24T06:52:30.704734+00:00 [running]> on host 7f96a5b4d944
[2024-07-24T06:52:32.422+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your.email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_file_import_dag' AIRFLOW_CTX_TASK_ID='get_s3_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T06:52:30.704734+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-24T06:52:30.704734+00:00'
[2024-07-24T06:52:32.423+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T06:52:32.454+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2024-07-24T06:52:32.455+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-07-24T06:52:32.940+0000] {logging_mixin.py:188} INFO - Location column data:
[2024-07-24T06:52:32.941+0000] {logging_mixin.py:188} INFO - 0    [55.2707828, 25.2048493]
1      [55.140902, 25.094612]
2    [55.2878512, 25.2242013]
3     [54.436645, 24.4180756]
4     [55.3705121, 25.311308]
Name: location, dtype: object
[2024-07-24T06:52:32.942+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-24T06:52:32.943+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T06:52:32.948+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=s3_file_import_dag, task_id=get_s3_data, run_id=manual__2024-07-24T06:52:30.704734+00:00, execution_date=20240724T065230, start_date=20240724T065232, end_date=20240724T065232
[2024-07-24T06:52:32.968+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T06:52:32.977+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T06:52:32.978+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
